/**
 * Byte-exact golden output for the typed C# (`standardToCsharp`) emitter over the
 * shared `combos` fixture. Consumed by `csharp.test.ts` to freeze the emitter's
 * output so any drift is visible in review. Generated fixture — do not hand-edit;
 * regenerate by re-running the emitter over `combos`.
 *
 * Shape: { [comboName]: emittedSource }.
 */
export const csharpGolden: Record<string, string> = {
  "simple-static": "using MockServer.Client;\nusing MockServer.Client.Models;\n\nusing var client = new MockServerClient(\"localhost\", 1080);\nclient.Upsert(new Expectation\n{\n    HttpRequest = new HttpRequest\n    {\n        Method = \"GET\",\n        Path = \"/api\",\n    },\n    HttpResponse = new HttpResponse\n    {\n        StatusCode = 200,\n        Headers = new Dictionary<string, List<string>>\n        {\n            [\"content-type\"] = new() { \"text/plain\" },\n        },\n        Body = \"hello\",\n    },\n});",
  "static-file-body-full": "using MockServer.Client;\nusing MockServer.Client.Models;\n\nusing var client = new MockServerClient(\"localhost\", 1080);\nclient.Upsert(new Expectation\n{\n    HttpRequest = new HttpRequest\n    {\n        Method = \"POST\",\n        Path = \"/orders\",\n    },\n    HttpResponse = new HttpResponse\n    {\n        StatusCode = 201,\n        ReasonPhrase = \"Created\",\n        Headers = new Dictionary<string, List<string>>\n        {\n            [\"X-Trace\"] = new() { \"abc\" },\n            [\"X-Env\"] = new() { \"prod\" },\n        },\n        Cookies = new Dictionary<string, string>\n        {\n            [\"session\"] = \"xyz\",\n            [\"theme\"] = \"dark\",\n        },\n        Body = new FileBody\n        {\n            FilePath = \"responses/order.json\",\n            ContentType = \"application/json\",\n            TemplateType = FileTemplateType.MUSTACHE,\n        },\n        Delay = new Delay { TimeUnit = TimeUnit.MILLISECONDS, Value = 250 },\n        ConnectionOptions = new ConnectionOptions { KeepAliveOverride = true, CloseSocket = false, SuppressContentLengthHeader = true },\n    },\n});",
  "json-body-jwt-secure": "using MockServer.Client;\nusing MockServer.Client.Models;\nusing System.Text.Json;\n\nusing var client = new MockServerClient(\"mock.example.com\", 443);\nclient.Upsert(new Expectation\n{\n    Priority = 5,\n    HttpRequest = new HttpRequest\n    {\n        Method = \"PUT\",\n        Path = \"/account\",\n        Headers = new Dictionary<string, List<string>>\n        {\n            [\"Accept\"] = new() { \"application/json\" },\n        },\n        QueryStringParameters = new Dictionary<string, List<string>>\n        {\n            [\"v\"] = new() { \"2\" },\n        },\n        Cookies = new Dictionary<string, string>\n        {\n            [\"sid\"] = \"1\",\n        },\n        PathParameters = new Dictionary<string, List<JsonElement>>\n        {\n            [\"id\"] = new() { JsonSerializer.SerializeToElement(\"42\") },\n        },\n        Body = Body.OfJson(\"{\\\"ok\\\":true,\\\"n\\\":3}\", \"STRICT\"),\n        Jwt = new Jwt\n        {\n            Header = \"x-auth\",\n            Scheme = \"Token\",\n            Claims = new Dictionary<string, string>\n            {\n                [\"sub\"] = \"user1\",\n                [\"role\"] = \"admin\",\n            },\n            Issuer = \"iss\",\n            Audience = \"aud\",\n            Algorithm = \"RS256\",\n        },\n        Secure = true,\n    },\n    HttpResponse = new HttpResponse\n    {\n        StatusCode = 200,\n    },\n    Times = Times.Exactly(2),\n    TimeToLive = TimeToLive.ExactlyTtl(TimeUnit.SECONDS, 60),\n});",
  "forward": "using MockServer.Client;\nusing MockServer.Client.Models;\n\nusing var client = new MockServerClient(\"localhost\", 1080);\nclient.Upsert(new Expectation\n{\n    HttpRequest = new HttpRequest\n    {\n        Method = \"GET\",\n        Path = \"/api\",\n    },\n    HttpForward = HttpForward.Forward()\n        .WithScheme(\"HTTPS\")\n        .WithHost(\"upstream.example.com\")\n        .WithPort(8443)\n        .Build(),\n});",
  "forward-override": "using MockServer.Client;\nusing MockServer.Client.Models;\n\nusing var client = new MockServerClient(\"localhost\", 1080);\nclient.Upsert(new Expectation\n{\n    HttpRequest = new HttpRequest\n    {\n        Method = \"GET\",\n        Path = \"/api\",\n    },\n    HttpOverrideForwardedRequest = new HttpOverrideForwardedRequest\n    {\n        HttpRequest = new HttpRequest\n        {\n            Method = \"PATCH\",\n            Path = \"/v2/api\",\n            Headers = new Dictionary<string, List<string>>\n            {\n                [\"X-Fwd\"] = new() { \"yes\" },\n                [\"Host\"] = new() { \"rewrite.example.com\" },\n            },\n            QueryStringParameters = new Dictionary<string, List<string>>\n            {\n                [\"debug\"] = new() { \"1\" },\n            },\n            Body = \"{\\\"patched\\\":true}\",\n            Secure = true,\n        },\n    },\n});",
  "callback": "using MockServer.Client;\nusing MockServer.Client.Models;\n\nusing var client = new MockServerClient(\"localhost\", 1080);\nclient.Upsert(new Expectation\n{\n    HttpRequest = new HttpRequest\n    {\n        Method = \"GET\",\n        Path = \"/api\",\n    },\n    HttpResponseClassCallback = new HttpClassCallback\n    {\n        CallbackClass = \"com.example.MyCallback\",\n    },\n});",
  "template-velocity": "using MockServer.Client;\nusing MockServer.Client.Models;\n\nusing var client = new MockServerClient(\"localhost\", 1080);\nclient.Upsert(new Expectation\n{\n    HttpRequest = new HttpRequest\n    {\n        Method = \"GET\",\n        Path = \"/api\",\n    },\n    HttpResponseTemplate = HttpTemplate.OfType(TemplateType.VELOCITY)\n        .WithTemplate(\"$!request.body\")\n        .Build(),\n});",
  "error": "using MockServer.Client;\nusing MockServer.Client.Models;\n\nusing var client = new MockServerClient(\"localhost\", 1080);\nclient.Upsert(new Expectation\n{\n    HttpRequest = new HttpRequest\n    {\n        Method = \"GET\",\n        Path = \"/api\",\n    },\n    HttpError = HttpError.Error()\n        .WithDropConnection(true)\n        .WithResponseBytes(\"AQIDBA==\")\n        .WithDelay(TimeUnit.SECONDS, 5)\n        .Build(),\n});",
  "forward-fallback": "using MockServer.Client;\nusing MockServer.Client.Models;\n\nusing var client = new MockServerClient(\"localhost\", 1080);\nclient.Upsert(new Expectation\n{\n    HttpRequest = new HttpRequest\n    {\n        Method = \"GET\",\n        Path = \"/api\",\n    },\n    HttpForwardWithFallback = new HttpForwardWithFallback\n    {\n        HttpForward = HttpForward.Forward()\n            .WithScheme(\"HTTP\")\n            .WithHost(\"primary.example.com\")\n            .WithPort(80)\n            .Build(),\n        FallbackResponse = new HttpResponse\n        {\n            StatusCode = 503,\n            Body = \"unavailable\",\n        },\n        FallbackOnStatusCodes = new List<int> { 500, 502, 503 },\n        FallbackOnTimeout = true,\n    },\n});",
  "websocket": "using MockServer.Client;\nusing MockServer.Client.Models;\n\nusing var client = new MockServerClient(\"localhost\", 1080);\nclient.Upsert(new Expectation\n{\n    HttpRequest = new HttpRequest\n    {\n        Method = \"GET\",\n        Path = \"/api\",\n    },\n    HttpWebSocketResponse = new HttpWebSocketResponse\n    {\n        Subprotocol = \"chat\",\n        Messages = new List<WebSocketMessage>\n        {\n            WebSocketMessage.OfText(\"hello\"),\n            WebSocketMessage.OfText(\"world\"),\n        },\n        Matchers = new List<WebSocketFrameMatcher>\n        {\n            new WebSocketFrameMatcher\n            {\n                FrameType = \"TEXT\",\n                TextMatcher = \"ping\",\n                Responses = new List<WebSocketMessage>\n                {\n                    WebSocketMessage.OfText(\"pong\"),\n                    WebSocketMessage.OfText(\"ack\"),\n                },\n            },\n        },\n    },\n});",
  "sse": "using MockServer.Client;\nusing MockServer.Client.Models;\n\nusing var client = new MockServerClient(\"localhost\", 1080);\nclient.Upsert(new Expectation\n{\n    HttpRequest = new HttpRequest\n    {\n        Method = \"GET\",\n        Path = \"/api\",\n    },\n    HttpSseResponse = new HttpSseResponse\n    {\n        StatusCode = 200,\n        Headers = new Dictionary<string, List<string>>\n        {\n            [\"Cache-Control\"] = new() { \"no-cache\" },\n        },\n        Events = new List<SseEvent>\n        {\n            new SseEvent\n            {\n                Event = \"msg\",\n                Data = \"tick\",\n                Id = \"1\",\n                Retry = 1000,\n            },\n        },\n    },\n});",
  "binary-response": "using MockServer.Client;\nusing MockServer.Client.Models;\n\nusing var client = new MockServerClient(\"localhost\", 1080);\nclient.Upsert(new Expectation\n{\n    HttpRequest = new HttpRequest\n    {\n        Method = \"GET\",\n        Path = \"/api\",\n    },\n    BinaryResponse = new BinaryResponse\n    {\n        BinaryData = \"SGVsbG8=\",\n    },\n});",
  "dns": "using MockServer.Client;\nusing MockServer.Client.Models;\n\nusing var client = new MockServerClient(\"localhost\", 1080);\nclient.Upsert(new Expectation\n{\n    HttpRequest = new HttpRequest\n    {\n        DnsName = \"example.com\",\n        DnsType = \"A\",\n        DnsClass = \"IN\",\n    },\n    DnsResponse = new DnsResponse\n    {\n        ResponseCode = \"NOERROR\",\n        AnswerRecords = new List<DnsRecord>\n        {\n            new DnsRecord\n            {\n                Name = \"example.com\",\n                Type = \"A\",\n                Ttl = 300,\n                Value = \"1.2.3.4\",\n            },\n        },\n    },\n});",
  "grpc-stream": "using MockServer.Client;\nusing MockServer.Client.Models;\n\nusing var client = new MockServerClient(\"localhost\", 1080);\nclient.Upsert(new Expectation\n{\n    HttpRequest = new HttpRequest\n    {\n        Method = \"GET\",\n        Path = \"/api\",\n    },\n    GrpcStreamResponse = new GrpcStreamResponse\n    {\n        StatusName = \"OK\",\n        Headers = new Dictionary<string, List<string>>\n        {\n            [\"grpc-encoding\"] = new() { \"identity\" },\n        },\n        Messages = new List<GrpcStreamMessage>\n        {\n            GrpcStreamMessage.OfJson(\"{\\\"a\\\":1}\"),\n            GrpcStreamMessage.OfJson(\"{\\\"b\\\":2}\"),\n        },\n    },\n});",
  "allOf-body": "using MockServer.Client;\nusing MockServer.Client.Models;\n\nusing var client = new MockServerClient(\"localhost\", 1080);\nclient.Upsert(new Expectation\n{\n    HttpRequest = new HttpRequest\n    {\n        Method = \"POST\",\n        Path = \"/api\",\n        Body = Body.OfAllOf(\n            Body.OfJson(\"{\\\"k\\\":1}\"),\n            Body.OfXPath(\"/a/b\"),\n            Body.OfRegex(\".*foo.*\")),\n    },\n    HttpResponse = new HttpResponse\n    {\n        StatusCode = 200,\n        Headers = new Dictionary<string, List<string>>\n        {\n            [\"content-type\"] = new() { \"text/plain\" },\n        },\n        Body = \"ok\",\n    },\n});",
  "special-chars-escaping": "using MockServer.Client;\nusing MockServer.Client.Models;\n\nusing var client = new MockServerClient(\"localhost\", 1080);\nclient.Upsert(new Expectation\n{\n    HttpRequest = new HttpRequest\n    {\n        Method = \"GET\",\n        Path = \"/a`b/c\\\"#d\",\n        Body = \"line1\\nline2 \\\"quoted\\\" `tick`\",\n    },\n    HttpResponse = new HttpResponse\n    {\n        StatusCode = 200,\n        Headers = new Dictionary<string, List<string>>\n        {\n            [\"content-type\"] = new() { \"text/plain\" },\n        },\n        Body = \"resp \\\"with\\\" `back`tick and #hash\",\n    },\n});",
  "capture-scenario-sideEffects": "using MockServer.Client;\nusing MockServer.Client.Models;\n\nusing var client = new MockServerClient(\"localhost\", 1080);\nclient.Upsert(new Expectation\n{\n    HttpRequest = new HttpRequest\n    {\n        Method = \"POST\",\n        Path = \"/checkout\",\n    },\n    HttpResponse = new HttpResponse\n    {\n        StatusCode = 200,\n        Headers = new Dictionary<string, List<string>>\n        {\n            [\"content-type\"] = new() { \"text/plain\" },\n        },\n        Body = \"ok\",\n    },\n    AfterActions = new List<AfterAction>\n    {\n        new AfterAction\n        {\n            HttpRequest = new HttpRequest\n            {\n                Method = \"POST\",\n                Path = \"/audit\",\n                Headers = new Dictionary<string, List<string>>\n                {\n                    [\"Host\"] = new() { \"audit.example.com\" },\n                },\n                Body = \"{\\\"logged\\\":true}\",\n            },\n        },\n    },\n    Capture = new List<CaptureRule>\n    {\n        CaptureRule.Of(\"jsonPath\", \"$.token\", \"authToken\"),\n    },\n    ScenarioName = \"login\",\n    ScenarioState = \"START\",\n    NewScenarioState = \"DONE\",\n});",
  "steps-pipeline": "using MockServer.Client;\nusing MockServer.Client.Models;\nusing System.Text.Json;\n\nusing var client = new MockServerClient(\"localhost\", 1080);\nclient.Upsert(new Expectation\n{\n    HttpRequest = new HttpRequest\n    {\n        Method = \"GET\",\n        Path = \"/pipeline\",\n    },\n    Steps = new List<ExpectationStep>\n    {\n        new ExpectationStep\n        {\n            HttpResponse = JsonSerializer.Deserialize<HttpResponse>(@\"{\"\"statusCode\"\":200,\"\"body\"\":\"\"step\"\"}\"),\n            Responder = true,\n        },\n        new ExpectationStep\n        {\n            HttpRequest = JsonSerializer.Deserialize<HttpRequest>(@\"{\"\"path\"\":\"\"/hook\"\"}\"),\n            Delay = new Delay { TimeUnit = TimeUnit.MILLISECONDS, Value = 100 },\n            Timeout = new Delay { TimeUnit = TimeUnit.SECONDS, Value = 2 },\n            FailurePolicy = ActionFailurePolicy.FAIL_FAST,\n        },\n    },\n});"
};
