/**
 * Byte-exact golden output for the Node client-library emitter (standardToNode),
 * extracted from the shared per-language golden (__fixtures__/emitterGolden.ts)
 * when the Node parity case was moved out of the shared byte-identity harness
 * into the Node-specific test (../node.test.ts).
 *
 * Shape: { [comboName]: emittedSource }, keyed by the shared `combos` fixture in
 * ../extractParityCases.ts. Generated — do not hand-edit; regenerate from
 * standardToNode over `combos` after a reviewed, intentional output change.
 */
export const nodeGolden: Record<string, string> = {
  "simple-static": "const { mockServerClient } = require('mockserver-client');\n\nmockServerClient(\"localhost\", 1080)\n  .mockAnyResponse({\n    \"httpRequest\": {\n      \"path\": \"/api\",\n      \"method\": \"GET\"\n    },\n    \"httpResponse\": {\n      \"statusCode\": 200,\n      \"body\": \"hello\",\n      \"headers\": {\n        \"content-type\": [\n          \"text/plain\"\n        ]\n      }\n    }\n  })\n  .then(\n    () => console.log(\"expectation created\"),\n    (error) => console.error(error)\n  );",
  "static-file-body-full": "const { mockServerClient } = require('mockserver-client');\n\nmockServerClient(\"localhost\", 1080)\n  .mockAnyResponse({\n    \"httpRequest\": {\n      \"path\": \"/orders\",\n      \"method\": \"POST\"\n    },\n    \"httpResponse\": {\n      \"statusCode\": 201,\n      \"body\": {\n        \"type\": \"FILE\",\n        \"filePath\": \"responses/order.json\",\n        \"templateType\": \"MUSTACHE\",\n        \"contentType\": \"application/json\"\n      },\n      \"headers\": {\n        \"X-Trace\": [\n          \"abc\"\n        ],\n        \"X-Env\": [\n          \"prod\"\n        ]\n      },\n      \"connectionOptions\": {\n        \"keepAliveOverride\": true,\n        \"closeSocket\": false,\n        \"suppressContentLengthHeader\": true\n      },\n      \"reasonPhrase\": \"Created\",\n      \"cookies\": {\n        \"session\": \"xyz\",\n        \"theme\": \"dark\"\n      },\n      \"delay\": {\n        \"timeUnit\": \"MILLISECONDS\",\n        \"value\": 250\n      }\n    }\n  })\n  .then(\n    () => console.log(\"expectation created\"),\n    (error) => console.error(error)\n  );",
  "json-body-jwt-secure": "const { mockServerClient } = require('mockserver-client');\n\nmockServerClient(\"mock.example.com\", 443)\n  .mockAnyResponse({\n    \"httpRequest\": {\n      \"path\": \"/account\",\n      \"method\": \"PUT\",\n      \"headers\": {\n        \"Accept\": [\n          \"application/json\"\n        ]\n      },\n      \"queryStringParameters\": {\n        \"v\": [\n          \"2\"\n        ]\n      },\n      \"cookies\": {\n        \"sid\": \"1\"\n      },\n      \"pathParameters\": {\n        \"id\": [\n          \"42\"\n        ]\n      },\n      \"body\": {\n        \"type\": \"JSON\",\n        \"json\": {\n          \"ok\": true,\n          \"n\": 3\n        },\n        \"matchType\": \"STRICT\"\n      },\n      \"jwt\": {\n        \"header\": \"x-auth\",\n        \"scheme\": \"Token\",\n        \"claims\": {\n          \"sub\": \"user1\",\n          \"role\": \"admin\"\n        },\n        \"issuer\": \"iss\",\n        \"audience\": \"aud\",\n        \"algorithm\": \"RS256\"\n      },\n      \"secure\": true\n    },\n    \"httpResponse\": {\n      \"statusCode\": 200\n    },\n    \"priority\": 5,\n    \"times\": {\n      \"remainingTimes\": 2,\n      \"unlimited\": false\n    },\n    \"timeToLive\": {\n      \"timeUnit\": \"SECONDS\",\n      \"timeToLive\": 60,\n      \"unlimited\": false\n    }\n  })\n  .then(\n    () => console.log(\"expectation created\"),\n    (error) => console.error(error)\n  );",
  "forward": "const { mockServerClient } = require('mockserver-client');\n\nmockServerClient(\"localhost\", 1080)\n  .mockAnyResponse({\n    \"httpRequest\": {\n      \"path\": \"/api\",\n      \"method\": \"GET\"\n    },\n    \"httpForward\": {\n      \"scheme\": \"HTTPS\",\n      \"host\": \"upstream.example.com\",\n      \"port\": 8443\n    }\n  })\n  .then(\n    () => console.log(\"expectation created\"),\n    (error) => console.error(error)\n  );",
  "forward-override": "const { mockServerClient } = require('mockserver-client');\n\nmockServerClient(\"localhost\", 1080)\n  .mockAnyResponse({\n    \"httpRequest\": {\n      \"path\": \"/api\",\n      \"method\": \"GET\"\n    },\n    \"httpOverrideForwardedRequest\": {\n      \"requestOverride\": {\n        \"method\": \"PATCH\",\n        \"secure\": true,\n        \"path\": \"/v2/api\",\n        \"headers\": {\n          \"X-Fwd\": [\n            \"yes\"\n          ],\n          \"Host\": [\n            \"rewrite.example.com\"\n          ]\n        },\n        \"queryStringParameters\": {\n          \"debug\": [\n            \"1\"\n          ]\n        },\n        \"body\": \"{\\\"patched\\\":true}\"\n      }\n    }\n  })\n  .then(\n    () => console.log(\"expectation created\"),\n    (error) => console.error(error)\n  );",
  "callback": "const { mockServerClient } = require('mockserver-client');\n\nmockServerClient(\"localhost\", 1080)\n  .mockAnyResponse({\n    \"httpRequest\": {\n      \"path\": \"/api\",\n      \"method\": \"GET\"\n    },\n    \"httpResponseClassCallback\": {\n      \"callbackClass\": \"com.example.MyCallback\"\n    }\n  })\n  .then(\n    () => console.log(\"expectation created\"),\n    (error) => console.error(error)\n  );",
  "template-velocity": "const { mockServerClient } = require('mockserver-client');\n\nmockServerClient(\"localhost\", 1080)\n  .mockAnyResponse({\n    \"httpRequest\": {\n      \"path\": \"/api\",\n      \"method\": \"GET\"\n    },\n    \"httpResponseTemplate\": {\n      \"templateType\": \"VELOCITY\",\n      \"template\": \"$!request.body\"\n    }\n  })\n  .then(\n    () => console.log(\"expectation created\"),\n    (error) => console.error(error)\n  );",
  "error": "const { mockServerClient } = require('mockserver-client');\n\nmockServerClient(\"localhost\", 1080)\n  .mockAnyResponse({\n    \"httpRequest\": {\n      \"path\": \"/api\",\n      \"method\": \"GET\"\n    },\n    \"httpError\": {\n      \"dropConnection\": true,\n      \"responseBytes\": \"AQIDBA==\",\n      \"delay\": {\n        \"timeUnit\": \"SECONDS\",\n        \"value\": 5\n      }\n    }\n  })\n  .then(\n    () => console.log(\"expectation created\"),\n    (error) => console.error(error)\n  );",
  "forward-fallback": "const { mockServerClient } = require('mockserver-client');\n\nmockServerClient(\"localhost\", 1080)\n  .mockAnyResponse({\n    \"httpRequest\": {\n      \"path\": \"/api\",\n      \"method\": \"GET\"\n    },\n    \"httpForwardWithFallback\": {\n      \"httpForward\": {\n        \"scheme\": \"HTTP\",\n        \"host\": \"primary.example.com\",\n        \"port\": 80\n      },\n      \"fallbackResponse\": {\n        \"statusCode\": 503,\n        \"body\": \"unavailable\"\n      },\n      \"fallbackOnStatusCodes\": [\n        500,\n        502,\n        503\n      ],\n      \"fallbackOnTimeout\": true\n    }\n  })\n  .then(\n    () => console.log(\"expectation created\"),\n    (error) => console.error(error)\n  );",
  "websocket": "const { mockServerClient } = require('mockserver-client');\n\nmockServerClient(\"localhost\", 1080)\n  .mockAnyResponse({\n    \"httpRequest\": {\n      \"path\": \"/api\",\n      \"method\": \"GET\"\n    },\n    \"httpWebSocketResponse\": {\n      \"subprotocol\": \"chat\",\n      \"messages\": [\n        {\n          \"text\": \"hello\"\n        },\n        {\n          \"text\": \"world\"\n        }\n      ],\n      \"matchers\": [\n        {\n          \"frameType\": \"TEXT\",\n          \"textMatcher\": \"ping\",\n          \"responses\": [\n            {\n              \"text\": \"pong\"\n            },\n            {\n              \"text\": \"ack\"\n            }\n          ]\n        }\n      ]\n    }\n  })\n  .then(\n    () => console.log(\"expectation created\"),\n    (error) => console.error(error)\n  );",
  "sse": "const { mockServerClient } = require('mockserver-client');\n\nmockServerClient(\"localhost\", 1080)\n  .mockAnyResponse({\n    \"httpRequest\": {\n      \"path\": \"/api\",\n      \"method\": \"GET\"\n    },\n    \"httpSseResponse\": {\n      \"statusCode\": 200,\n      \"headers\": {\n        \"Cache-Control\": [\n          \"no-cache\"\n        ]\n      },\n      \"events\": [\n        {\n          \"event\": \"msg\",\n          \"data\": \"tick\",\n          \"id\": \"1\",\n          \"retry\": 1000\n        }\n      ]\n    }\n  })\n  .then(\n    () => console.log(\"expectation created\"),\n    (error) => console.error(error)\n  );",
  "binary-response": "const { mockServerClient } = require('mockserver-client');\n\nmockServerClient(\"localhost\", 1080)\n  .mockAnyResponse({\n    \"httpRequest\": {\n      \"path\": \"/api\",\n      \"method\": \"GET\"\n    },\n    \"binaryResponse\": {\n      \"binaryData\": \"SGVsbG8=\"\n    }\n  })\n  .then(\n    () => console.log(\"expectation created\"),\n    (error) => console.error(error)\n  );",
  "dns": "const { mockServerClient } = require('mockserver-client');\n\nmockServerClient(\"localhost\", 1080)\n  .mockAnyResponse({\n    \"httpRequest\": {\n      \"dnsName\": \"example.com\",\n      \"dnsType\": \"A\",\n      \"dnsClass\": \"IN\"\n    },\n    \"dnsResponse\": {\n      \"responseCode\": \"NOERROR\",\n      \"answerRecords\": [\n        {\n          \"name\": \"example.com\",\n          \"type\": \"A\",\n          \"ttl\": 300,\n          \"value\": \"1.2.3.4\"\n        }\n      ]\n    }\n  })\n  .then(\n    () => console.log(\"expectation created\"),\n    (error) => console.error(error)\n  );",
  "grpc-stream": "const { mockServerClient } = require('mockserver-client');\n\nmockServerClient(\"localhost\", 1080)\n  .mockAnyResponse({\n    \"httpRequest\": {\n      \"path\": \"/api\",\n      \"method\": \"GET\"\n    },\n    \"grpcStreamResponse\": {\n      \"statusName\": \"OK\",\n      \"headers\": {\n        \"grpc-encoding\": [\n          \"identity\"\n        ]\n      },\n      \"messages\": [\n        {\n          \"json\": \"{\\\"a\\\":1}\"\n        },\n        {\n          \"json\": \"{\\\"b\\\":2}\"\n        }\n      ]\n    }\n  })\n  .then(\n    () => console.log(\"expectation created\"),\n    (error) => console.error(error)\n  );",
  "allOf-body": "const { mockServerClient } = require('mockserver-client');\n\nmockServerClient(\"localhost\", 1080)\n  .mockAnyResponse({\n    \"httpRequest\": {\n      \"path\": \"/api\",\n      \"method\": \"POST\",\n      \"body\": {\n        \"type\": \"ALL_OF\",\n        \"bodyAllOf\": [\n          {\n            \"type\": \"JSON\",\n            \"json\": {\n              \"k\": 1\n            }\n          },\n          {\n            \"type\": \"XPATH\",\n            \"xpath\": \"/a/b\"\n          },\n          {\n            \"type\": \"REGEX\",\n            \"regex\": \".*foo.*\"\n          }\n        ]\n      }\n    },\n    \"httpResponse\": {\n      \"statusCode\": 200,\n      \"body\": \"ok\",\n      \"headers\": {\n        \"content-type\": [\n          \"text/plain\"\n        ]\n      }\n    }\n  })\n  .then(\n    () => console.log(\"expectation created\"),\n    (error) => console.error(error)\n  );",
  "special-chars-escaping": "const { mockServerClient } = require('mockserver-client');\n\nmockServerClient(\"localhost\", 1080)\n  .mockAnyResponse({\n    \"httpRequest\": {\n      \"path\": \"/a`b/c\\\"#d\",\n      \"method\": \"GET\",\n      \"body\": \"line1\\nline2 \\\"quoted\\\" `tick`\"\n    },\n    \"httpResponse\": {\n      \"statusCode\": 200,\n      \"body\": \"resp \\\"with\\\" `back`tick and #hash\",\n      \"headers\": {\n        \"content-type\": [\n          \"text/plain\"\n        ]\n      }\n    }\n  })\n  .then(\n    () => console.log(\"expectation created\"),\n    (error) => console.error(error)\n  );",
  "capture-scenario-sideEffects": "const { mockServerClient } = require('mockserver-client');\n\nmockServerClient(\"localhost\", 1080)\n  .mockAnyResponse({\n    \"httpRequest\": {\n      \"path\": \"/checkout\",\n      \"method\": \"POST\"\n    },\n    \"httpResponse\": {\n      \"statusCode\": 200,\n      \"body\": \"ok\",\n      \"headers\": {\n        \"content-type\": [\n          \"text/plain\"\n        ]\n      }\n    },\n    \"afterActions\": [\n      {\n        \"httpRequest\": {\n          \"path\": \"/audit\",\n          \"method\": \"POST\",\n          \"headers\": {\n            \"Host\": [\n              \"audit.example.com\"\n            ]\n          },\n          \"body\": \"{\\\"logged\\\":true}\"\n        }\n      }\n    ],\n    \"capture\": [\n      {\n        \"source\": \"jsonPath\",\n        \"expression\": \"$.token\",\n        \"into\": \"authToken\"\n      }\n    ],\n    \"scenarioName\": \"login\",\n    \"scenarioState\": \"START\",\n    \"newScenarioState\": \"DONE\"\n  })\n  .then(\n    () => console.log(\"expectation created\"),\n    (error) => console.error(error)\n  );",
  "steps-pipeline": "const { mockServerClient } = require('mockserver-client');\n\nmockServerClient(\"localhost\", 1080)\n  .mockAnyResponse({\n    \"httpRequest\": {\n      \"path\": \"/pipeline\",\n      \"method\": \"GET\"\n    },\n    \"steps\": [\n      {\n        \"httpResponse\": {\n          \"statusCode\": 200,\n          \"body\": \"step\"\n        },\n        \"responder\": true\n      },\n      {\n        \"httpRequest\": {\n          \"path\": \"/hook\"\n        },\n        \"delay\": {\n          \"timeUnit\": \"MILLISECONDS\",\n          \"value\": 100\n        },\n        \"timeout\": {\n          \"timeUnit\": \"SECONDS\",\n          \"value\": 2\n        },\n        \"failurePolicy\": \"FAIL_FAST\"\n      }\n    ]\n  })\n  .then(\n    () => console.log(\"expectation created\"),\n    (error) => console.error(error)\n  );"
};
