/**
 * Golden fixture for the typed Python client-code emitter ({@link ../python.ts}).
 *
 * Generated once and committed as an explicit, self-documenting proof of the
 * emitter's exact output across the {@link ../extractParityCases.ts} `combos`.
 * Regenerate deliberately (never hand-edit) when the emitter changes; the
 * accompanying execution test proves each snippet, when run against the in-repo
 * `mockserver-client-python`, reconstructs the SAME expectation the JSON tab
 * produces (see pythonCodegen.test.ts).
 */
export const pythonGolden: Record<string, string> = {
  "simple-static": "from mockserver import (\n    Expectation,\n    HttpRequest,\n    HttpResponse,\n    KeyToMultiValue,\n    MockServerClient,\n)\n\nMockServerClient(\"localhost\", 1080).upsert(\n    Expectation(\n        http_request=HttpRequest(\n            method=\"GET\",\n            path=\"/api\",\n        ),\n        http_response=HttpResponse(\n            status_code=200,\n            body=\"hello\",\n            headers=[KeyToMultiValue(name=\"content-type\", values=[\"text/plain\"])],\n        ),\n    )\n)",
  "static-file-body-full": "from mockserver import (\n    Body,\n    ConnectionOptions,\n    Delay,\n    Expectation,\n    HttpRequest,\n    HttpResponse,\n    KeyToMultiValue,\n    MockServerClient,\n)\n\nMockServerClient(\"localhost\", 1080).upsert(\n    Expectation(\n        http_request=HttpRequest(\n            method=\"POST\",\n            path=\"/orders\",\n        ),\n        http_response=HttpResponse(\n            status_code=201,\n            reason_phrase=\"Created\",\n            body=Body(type=\"FILE\", file_path=\"responses/order.json\", template_type=\"MUSTACHE\", content_type=\"application/json\"),\n            headers=[\n                KeyToMultiValue(name=\"X-Trace\", values=[\"abc\"]),\n                KeyToMultiValue(name=\"X-Env\", values=[\"prod\"]),\n            ],\n            cookies=[\n                KeyToMultiValue(name=\"session\", values=[\"xyz\"]),\n                KeyToMultiValue(name=\"theme\", values=[\"dark\"]),\n            ],\n            delay=Delay(time_unit=\"MILLISECONDS\", value=250),\n            connection_options=ConnectionOptions(\n                keep_alive_override=True,\n                close_socket=False,\n                suppress_content_length_header=True,\n            ),\n        ),\n    )\n)",
  "json-body-jwt-secure": "from mockserver import (\n    Body,\n    Expectation,\n    HttpRequest,\n    HttpResponse,\n    Jwt,\n    KeyToMultiValue,\n    MockServerClient,\n    Times,\n    TimeToLive,\n)\n\nMockServerClient(\"mock.example.com\", 443).upsert(\n    Expectation(\n        http_request=HttpRequest(\n            method=\"PUT\",\n            path=\"/account\",\n            headers=[KeyToMultiValue(name=\"Accept\", values=[\"application/json\"])],\n            query_string_parameters=[KeyToMultiValue(name=\"v\", values=[\"2\"])],\n            cookies=[KeyToMultiValue(name=\"sid\", values=[\"1\"])],\n            path_parameters=[KeyToMultiValue(name=\"id\", values=[\"42\"])],\n            body=Body(\n                type=\"JSON\",\n                json={\n                    \"ok\": True,\n                    \"n\": 3\n                },\n                match_type=\"STRICT\",\n            ),\n            jwt=Jwt(\n                claims={\n                    \"sub\": \"user1\",\n                    \"role\": \"admin\"\n                },\n                issuer=\"iss\",\n                audience=\"aud\",\n                algorithm=\"RS256\",\n                header=\"x-auth\",\n                scheme=\"Token\",\n            ),\n            secure=True,\n        ),\n        http_response=HttpResponse(\n            status_code=200,\n        ),\n        priority=5,\n        times=Times(remaining_times=2, unlimited=False),\n        time_to_live=TimeToLive(time_unit=\"SECONDS\", time_to_live=60, unlimited=False),\n    )\n)",
  "forward": "from mockserver import (\n    Expectation,\n    HttpForward,\n    HttpRequest,\n    MockServerClient,\n)\n\nMockServerClient(\"localhost\", 1080).upsert(\n    Expectation(\n        http_request=HttpRequest(\n            method=\"GET\",\n            path=\"/api\",\n        ),\n        http_forward=HttpForward(\n            scheme=\"HTTPS\",\n            host=\"upstream.example.com\",\n            port=8443,\n        ),\n    )\n)",
  "forward-override": "from mockserver import (\n    Expectation,\n    HttpOverrideForwardedRequest,\n    HttpRequest,\n    KeyToMultiValue,\n    MockServerClient,\n)\n\nMockServerClient(\"localhost\", 1080).upsert(\n    Expectation(\n        http_request=HttpRequest(\n            method=\"GET\",\n            path=\"/api\",\n        ),\n        http_override_forwarded_request=HttpOverrideForwardedRequest(\n            http_request=HttpRequest(\n                method=\"PATCH\",\n                path=\"/v2/api\",\n                headers=[\n                    KeyToMultiValue(name=\"X-Fwd\", values=[\"yes\"]),\n                    KeyToMultiValue(name=\"Host\", values=[\"rewrite.example.com\"]),\n                ],\n                query_string_parameters=[KeyToMultiValue(name=\"debug\", values=[\"1\"])],\n                body=\"{\\\"patched\\\":true}\",\n                secure=True,\n            ),\n        ),\n    )\n)",
  "callback": "from mockserver import (\n    Expectation,\n    HttpClassCallback,\n    HttpRequest,\n    MockServerClient,\n)\n\nMockServerClient(\"localhost\", 1080).upsert(\n    Expectation(\n        http_request=HttpRequest(\n            method=\"GET\",\n            path=\"/api\",\n        ),\n        http_response_class_callback=HttpClassCallback(\n            callback_class=\"com.example.MyCallback\",\n        ),\n    )\n)",
  "template-velocity": "from mockserver import (\n    Expectation,\n    HttpRequest,\n    HttpTemplate,\n    MockServerClient,\n)\n\nMockServerClient(\"localhost\", 1080).upsert(\n    Expectation(\n        http_request=HttpRequest(\n            method=\"GET\",\n            path=\"/api\",\n        ),\n        http_response_template=HttpTemplate(\n            template_type=\"VELOCITY\",\n            template=\"$!request.body\",\n        ),\n    )\n)",
  "error": "from mockserver import (\n    Delay,\n    Expectation,\n    HttpError,\n    HttpRequest,\n    MockServerClient,\n)\n\nMockServerClient(\"localhost\", 1080).upsert(\n    Expectation(\n        http_request=HttpRequest(\n            method=\"GET\",\n            path=\"/api\",\n        ),\n        http_error=HttpError(\n            drop_connection=True,\n            response_bytes=\"AQIDBA==\",\n            delay=Delay(time_unit=\"SECONDS\", value=5),\n        ),\n    )\n)",
  "forward-fallback": "from mockserver import (\n    Expectation,\n    HttpForward,\n    HttpForwardWithFallback,\n    HttpRequest,\n    HttpResponse,\n    MockServerClient,\n)\n\nMockServerClient(\"localhost\", 1080).upsert(\n    Expectation(\n        http_request=HttpRequest(\n            method=\"GET\",\n            path=\"/api\",\n        ),\n        http_forward_with_fallback=HttpForwardWithFallback(\n            http_forward=HttpForward(\n                scheme=\"HTTP\",\n                host=\"primary.example.com\",\n                port=80,\n            ),\n            fallback_response=HttpResponse(\n                status_code=503,\n                body=\"unavailable\",\n            ),\n            fallback_on_status_codes=[500, 502, 503],\n            fallback_on_timeout=True,\n        ),\n    )\n)",
  "websocket": "from mockserver import (\n    Expectation,\n    HttpRequest,\n    HttpWebSocketResponse,\n    MockServerClient,\n    WebSocketFrameMatcher,\n    WebSocketMessage,\n)\n\nMockServerClient(\"localhost\", 1080).upsert(\n    Expectation(\n        http_request=HttpRequest(\n            method=\"GET\",\n            path=\"/api\",\n        ),\n        http_websocket_response=HttpWebSocketResponse(\n            subprotocol=\"chat\",\n            messages=[\n                WebSocketMessage(text=\"hello\"),\n                WebSocketMessage(text=\"world\"),\n            ],\n            matchers=[\n                WebSocketFrameMatcher(\n                    frame_type=\"TEXT\",\n                    text_matcher=\"ping\",\n                    responses=[\n                        WebSocketMessage(text=\"pong\"),\n                        WebSocketMessage(text=\"ack\"),\n                    ],\n                ),\n            ],\n        ),\n    )\n)",
  "sse": "from mockserver import (\n    Expectation,\n    HttpRequest,\n    HttpSseResponse,\n    KeyToMultiValue,\n    MockServerClient,\n    SseEvent,\n)\n\nMockServerClient(\"localhost\", 1080).upsert(\n    Expectation(\n        http_request=HttpRequest(\n            method=\"GET\",\n            path=\"/api\",\n        ),\n        http_sse_response=HttpSseResponse(\n            status_code=200,\n            headers=[KeyToMultiValue(name=\"Cache-Control\", values=[\"no-cache\"])],\n            events=[SseEvent(event=\"msg\", data=\"tick\", id=\"1\", retry=1000)],\n        ),\n    )\n)",
  "binary-response": "from mockserver import (\n    BinaryResponse,\n    Expectation,\n    HttpRequest,\n    MockServerClient,\n)\n\nMockServerClient(\"localhost\", 1080).upsert(\n    Expectation(\n        http_request=HttpRequest(\n            method=\"GET\",\n            path=\"/api\",\n        ),\n        binary_response=BinaryResponse(\n            binary_data=\"SGVsbG8=\",\n        ),\n    )\n)",
  "dns": "from mockserver import (\n    DnsRecord,\n    DnsRequestDefinition,\n    DnsResponse,\n    Expectation,\n    MockServerClient,\n)\n\nMockServerClient(\"localhost\", 1080).upsert(\n    Expectation(\n        http_request=DnsRequestDefinition(\n            dns_name=\"example.com\",\n            dns_type=\"A\",\n            dns_class=\"IN\",\n        ),\n        dns_response=DnsResponse(\n            response_code=\"NOERROR\",\n            answer_records=[DnsRecord(name=\"example.com\", type=\"A\", ttl=300, value=\"1.2.3.4\")],\n        ),\n    )\n)",
  "grpc-stream": "from mockserver import (\n    Expectation,\n    GrpcStreamMessage,\n    GrpcStreamResponse,\n    HttpRequest,\n    KeyToMultiValue,\n    MockServerClient,\n)\n\nMockServerClient(\"localhost\", 1080).upsert(\n    Expectation(\n        http_request=HttpRequest(\n            method=\"GET\",\n            path=\"/api\",\n        ),\n        grpc_stream_response=GrpcStreamResponse(\n            status_name=\"OK\",\n            headers=[KeyToMultiValue(name=\"grpc-encoding\", values=[\"identity\"])],\n            messages=[\n                GrpcStreamMessage(json=\"{\\\"a\\\":1}\"),\n                GrpcStreamMessage(json=\"{\\\"b\\\":2}\"),\n            ],\n        ),\n    )\n)",
  "allOf-body": "from mockserver import (\n    AllOfBody,\n    Body,\n    Expectation,\n    HttpRequest,\n    HttpResponse,\n    KeyToMultiValue,\n    MockServerClient,\n    RegexBody,\n    XPathBody,\n)\n\nMockServerClient(\"localhost\", 1080).upsert(\n    Expectation(\n        http_request=HttpRequest(\n            method=\"POST\",\n            path=\"/api\",\n            body=AllOfBody(\n                body_all_of=[\n                    Body(\n                        type=\"JSON\",\n                        json={\n                            \"k\": 1\n                        },\n                    ),\n                    XPathBody(xpath=\"/a/b\"),\n                    RegexBody(regex=\".*foo.*\"),\n                ],\n            ),\n        ),\n        http_response=HttpResponse(\n            status_code=200,\n            body=\"ok\",\n            headers=[KeyToMultiValue(name=\"content-type\", values=[\"text/plain\"])],\n        ),\n    )\n)",
  "special-chars-escaping": "from mockserver import (\n    Expectation,\n    HttpRequest,\n    HttpResponse,\n    KeyToMultiValue,\n    MockServerClient,\n)\n\nMockServerClient(\"localhost\", 1080).upsert(\n    Expectation(\n        http_request=HttpRequest(\n            method=\"GET\",\n            path=\"/a`b/c\\\"#d\",\n            body=\"line1\\nline2 \\\"quoted\\\" `tick`\",\n        ),\n        http_response=HttpResponse(\n            status_code=200,\n            body=\"resp \\\"with\\\" `back`tick and #hash\",\n            headers=[KeyToMultiValue(name=\"content-type\", values=[\"text/plain\"])],\n        ),\n    )\n)",
  "capture-scenario-sideEffects": "from mockserver import (\n    AfterAction,\n    CaptureRule,\n    Expectation,\n    HttpRequest,\n    HttpResponse,\n    KeyToMultiValue,\n    MockServerClient,\n)\n\nMockServerClient(\"localhost\", 1080).upsert(\n    Expectation(\n        http_request=HttpRequest(\n            method=\"POST\",\n            path=\"/checkout\",\n        ),\n        http_response=HttpResponse(\n            status_code=200,\n            body=\"ok\",\n            headers=[KeyToMultiValue(name=\"content-type\", values=[\"text/plain\"])],\n        ),\n        after_actions=[\n            AfterAction(\n                http_request=HttpRequest(\n                    method=\"POST\",\n                    path=\"/audit\",\n                    headers=[KeyToMultiValue(name=\"Host\", values=[\"audit.example.com\"])],\n                    body=\"{\\\"logged\\\":true}\",\n                ),\n            ),\n        ],\n        capture=[CaptureRule(source=\"jsonPath\", expression=\"$.token\", into=\"authToken\")],\n        scenario_name=\"login\",\n        scenario_state=\"START\",\n        new_scenario_state=\"DONE\",\n    )\n)",
  "steps-pipeline": "from mockserver import (\n    Delay,\n    Expectation,\n    ExpectationStep,\n    HttpRequest,\n    HttpResponse,\n    MockServerClient,\n)\n\nMockServerClient(\"localhost\", 1080).upsert(\n    Expectation(\n        http_request=HttpRequest(\n            method=\"GET\",\n            path=\"/pipeline\",\n        ),\n        steps=[\n            ExpectationStep(\n                http_response=HttpResponse(\n                    status_code=200,\n                    body=\"step\",\n                ),\n                responder=True,\n            ),\n            ExpectationStep(\n                http_request=HttpRequest(\n                    path=\"/hook\",\n                ),\n                delay=Delay(time_unit=\"MILLISECONDS\", value=100),\n                timeout=Delay(time_unit=\"SECONDS\", value=2),\n                failure_policy=\"FAIL_FAST\",\n            ),\n        ],\n    )\n)"
};
