/**
 * Byte-exact golden output for the TYPED Ruby client-library emitter
 * ({@link ../ruby.ts}). Consumed by {@link ../ruby.test.ts} to guard the
 * emitter against accidental output drift. Regenerate deliberately (after a
 * reviewed change) by re-running the emitter over the shared combos in
 * {@link ../extractParityCases.ts}; never hand-edit.
 */
export const rubyGolden: Record<string, string> = {
  "simple-static": "require 'mockserver-client'\n\nclient = MockServer::Client.new('localhost', 1080)\n\nclient.upsert(\n  MockServer::Expectation.new(\n    http_request: MockServer::HttpRequest.new(\n      method: \"GET\",\n      path: \"/api\"\n    ),\n    http_response: MockServer::HttpResponse.new(\n      status_code: 200,\n      body: \"hello\",\n      headers: [\n        MockServer::KeyToMultiValue.new(name: \"content-type\", values: [\"text/plain\"])\n      ]\n    )\n  )\n)",
  "static-file-body-full": "require 'mockserver-client'\n\nclient = MockServer::Client.new('localhost', 1080)\n\nclient.upsert(\n  MockServer::Expectation.new(\n    http_request: MockServer::HttpRequest.new(\n      method: \"POST\",\n      path: \"/orders\"\n    ),\n    http_response: MockServer::HttpResponse.new(\n      status_code: 201,\n      reason_phrase: \"Created\",\n      body: MockServer::Body.new(\n        type: \"FILE\",\n        file_path: \"responses/order.json\",\n        template_type: \"MUSTACHE\",\n        content_type: \"application/json\"\n      ),\n      headers: [\n        MockServer::KeyToMultiValue.new(name: \"X-Trace\", values: [\"abc\"]),\n        MockServer::KeyToMultiValue.new(name: \"X-Env\", values: [\"prod\"])\n      ],\n      cookies: [\n        MockServer::KeyToMultiValue.new(name: \"session\", values: [\"xyz\"]),\n        MockServer::KeyToMultiValue.new(name: \"theme\", values: [\"dark\"])\n      ],\n      connection_options: MockServer::ConnectionOptions.new(\n        keep_alive_override: true,\n        close_socket: false,\n        suppress_content_length_header: true\n      ),\n      delay: MockServer::Delay.new(\n        time_unit: \"MILLISECONDS\",\n        value: 250\n      )\n    )\n  )\n)",
  "json-body-jwt-secure": "require 'mockserver-client'\n\nclient = MockServer::Client.new('mock.example.com', 443)\n\nclient.upsert(\n  MockServer::Expectation.new(\n    http_request: MockServer::HttpRequest.new(\n      method: \"PUT\",\n      path: \"/account\",\n      headers: [\n        MockServer::KeyToMultiValue.new(name: \"Accept\", values: [\"application/json\"])\n      ],\n      query_string_parameters: [\n        MockServer::KeyToMultiValue.new(name: \"v\", values: [\"2\"])\n      ],\n      cookies: [\n        MockServer::KeyToMultiValue.new(name: \"sid\", values: [\"1\"])\n      ],\n      path_parameters: [\n        MockServer::KeyToMultiValue.new(name: \"id\", values: [\"42\"])\n      ],\n      body: MockServer::Body.new(\n        type: \"JSON\",\n        json: {\n          \"ok\" => true,\n          \"n\" => 3\n        },\n        match_type: \"STRICT\"\n      ),\n      secure: true,\n      jwt: MockServer::Jwt.new(\n        header: \"x-auth\",\n        scheme: \"Token\",\n        issuer: \"iss\",\n        audience: \"aud\",\n        algorithm: \"RS256\",\n        claims: {\n          \"sub\" => \"user1\",\n          \"role\" => \"admin\"\n        }\n      )\n    ),\n    http_response: MockServer::HttpResponse.new(\n      status_code: 200\n    ),\n    priority: 5,\n    times: MockServer::Times.new(\n      remaining_times: 2,\n      unlimited: false\n    ),\n    time_to_live: MockServer::TimeToLive.new(\n      time_unit: \"SECONDS\",\n      time_to_live: 60,\n      unlimited: false\n    )\n  )\n)",
  "forward": "require 'mockserver-client'\n\nclient = MockServer::Client.new('localhost', 1080)\n\nclient.upsert(\n  MockServer::Expectation.new(\n    http_request: MockServer::HttpRequest.new(\n      method: \"GET\",\n      path: \"/api\"\n    ),\n    http_forward: MockServer::HttpForward.new(\n      host: \"upstream.example.com\",\n      port: 8443,\n      scheme: \"HTTPS\"\n    )\n  )\n)",
  "forward-override": "require 'mockserver-client'\n\nclient = MockServer::Client.new('localhost', 1080)\n\nclient.upsert(\n  MockServer::Expectation.new(\n    http_request: MockServer::HttpRequest.new(\n      method: \"GET\",\n      path: \"/api\"\n    ),\n    http_override_forwarded_request: {\n      \"requestOverride\" => {\n        \"method\" => \"PATCH\",\n        \"secure\" => true,\n        \"path\" => \"/v2/api\",\n        \"headers\" => {\n          \"X-Fwd\" => [\n            \"yes\"\n          ],\n          \"Host\" => [\n            \"rewrite.example.com\"\n          ]\n        },\n        \"queryStringParameters\" => {\n          \"debug\" => [\n            \"1\"\n          ]\n        },\n        \"body\" => \"{\\\"patched\\\":true}\"\n      }\n    }\n  )\n)",
  "callback": "require 'mockserver-client'\n\nclient = MockServer::Client.new('localhost', 1080)\n\nclient.upsert(\n  MockServer::Expectation.new(\n    http_request: MockServer::HttpRequest.new(\n      method: \"GET\",\n      path: \"/api\"\n    ),\n    http_response_class_callback: MockServer::HttpClassCallback.new(\n      callback_class: \"com.example.MyCallback\"\n    )\n  )\n)",
  "template-velocity": "require 'mockserver-client'\n\nclient = MockServer::Client.new('localhost', 1080)\n\nclient.upsert(\n  MockServer::Expectation.new(\n    http_request: MockServer::HttpRequest.new(\n      method: \"GET\",\n      path: \"/api\"\n    ),\n    http_response_template: MockServer::HttpTemplate.new(\n      template_type: \"VELOCITY\",\n      template: \"$!request.body\"\n    )\n  )\n)",
  "error": "require 'mockserver-client'\n\nclient = MockServer::Client.new('localhost', 1080)\n\nclient.upsert(\n  MockServer::Expectation.new(\n    http_request: MockServer::HttpRequest.new(\n      method: \"GET\",\n      path: \"/api\"\n    ),\n    http_error: MockServer::HttpError.new(\n      drop_connection: true,\n      response_bytes: \"AQIDBA==\",\n      delay: MockServer::Delay.new(\n        time_unit: \"SECONDS\",\n        value: 5\n      )\n    )\n  )\n)",
  "forward-fallback": "require 'mockserver-client'\n\nclient = MockServer::Client.new('localhost', 1080)\n\nclient.upsert(\n  MockServer::Expectation.new(\n    http_request: MockServer::HttpRequest.new(\n      method: \"GET\",\n      path: \"/api\"\n    ),\n    http_forward_with_fallback: MockServer::HttpForwardWithFallback.new(\n      http_forward: MockServer::HttpForward.new(\n        host: \"primary.example.com\",\n        port: 80,\n        scheme: \"HTTP\"\n      ),\n      fallback_response: MockServer::HttpResponse.new(\n        status_code: 503,\n        body: \"unavailable\"\n      ),\n      fallback_on_status_codes: [\n        500,\n        502,\n        503\n      ],\n      fallback_on_timeout: true\n    )\n  )\n)",
  "websocket": "require 'mockserver-client'\n\nclient = MockServer::Client.new('localhost', 1080)\n\nclient.upsert(\n  MockServer::Expectation.new(\n    http_request: MockServer::HttpRequest.new(\n      method: \"GET\",\n      path: \"/api\"\n    ),\n    http_websocket_response: MockServer::HttpWebSocketResponse.new(\n      subprotocol: \"chat\",\n      messages: [\n        MockServer::WebSocketMessage.new(\n          text: \"hello\"\n        ),\n        MockServer::WebSocketMessage.new(\n          text: \"world\"\n        )\n      ],\n      matchers: [\n        MockServer::WebSocketFrameMatcher.new(\n          frame_type: \"TEXT\",\n          text_matcher: \"ping\",\n          responses: [\n          MockServer::WebSocketMessage.new(\n            text: \"pong\"\n          ),\n          MockServer::WebSocketMessage.new(\n            text: \"ack\"\n          )\n        ]\n        )\n      ]\n    )\n  )\n)",
  "sse": "require 'mockserver-client'\n\nclient = MockServer::Client.new('localhost', 1080)\n\nclient.upsert(\n  MockServer::Expectation.new(\n    http_request: MockServer::HttpRequest.new(\n      method: \"GET\",\n      path: \"/api\"\n    ),\n    http_sse_response: MockServer::HttpSseResponse.new(\n      status_code: 200,\n      headers: [\n        MockServer::KeyToMultiValue.new(name: \"Cache-Control\", values: [\"no-cache\"])\n      ],\n      events: [\n        MockServer::SseEvent.new(\n          event: \"msg\",\n          data: \"tick\",\n          id: \"1\",\n          retry_ms: 1000\n        )\n      ]\n    )\n  )\n)",
  "binary-response": "require 'mockserver-client'\n\nclient = MockServer::Client.new('localhost', 1080)\n\nclient.upsert(\n  MockServer::Expectation.new(\n    http_request: MockServer::HttpRequest.new(\n      method: \"GET\",\n      path: \"/api\"\n    ),\n    binary_response: MockServer::BinaryResponse.new(\n      binary_data: \"SGVsbG8=\"\n    )\n  )\n)",
  "dns": "require 'mockserver-client'\n\nclient = MockServer::Client.new('localhost', 1080)\n\nclient.upsert(\n  MockServer::Expectation.new(\n    http_request: MockServer::HttpRequest.new(\n      dns_name: \"example.com\",\n      dns_type: \"A\",\n      dns_class: \"IN\"\n    ),\n    dns_response: MockServer::DnsResponse.new(\n      response_code: \"NOERROR\",\n      answer_records: [\n        MockServer::DnsRecord.new(\n          name: \"example.com\",\n          type: \"A\",\n          ttl: 300,\n          value: \"1.2.3.4\"\n        )\n      ]\n    )\n  )\n)",
  "grpc-stream": "require 'mockserver-client'\n\nclient = MockServer::Client.new('localhost', 1080)\n\nclient.upsert(\n  MockServer::Expectation.new(\n    http_request: MockServer::HttpRequest.new(\n      method: \"GET\",\n      path: \"/api\"\n    ),\n    grpc_stream_response: MockServer::GrpcStreamResponse.new(\n      status_name: \"OK\",\n      headers: [\n        MockServer::KeyToMultiValue.new(name: \"grpc-encoding\", values: [\"identity\"])\n      ],\n      messages: [\n        MockServer::GrpcStreamMessage.new(\n          json: \"{\\\"a\\\":1}\"\n        ),\n        MockServer::GrpcStreamMessage.new(\n          json: \"{\\\"b\\\":2}\"\n        )\n      ]\n    )\n  )\n)",
  "allOf-body": "require 'mockserver-client'\n\nclient = MockServer::Client.new('localhost', 1080)\n\nclient.upsert(\n  MockServer::Expectation.new(\n    http_request: MockServer::HttpRequest.new(\n      method: \"POST\",\n      path: \"/api\",\n      body: MockServer::Body.new(\n        type: \"ALL_OF\",\n        body_all_of: [\n          MockServer::Body.new(\n          type: \"JSON\",\n          json: {\n            \"k\" => 1\n          }\n        ),\n          MockServer::Body.new(\n          type: \"XPATH\",\n          xpath: \"/a/b\"\n        ),\n          MockServer::Body.new(\n          type: \"REGEX\",\n          regex: \".*foo.*\"\n        )\n        ]\n      )\n    ),\n    http_response: MockServer::HttpResponse.new(\n      status_code: 200,\n      body: \"ok\",\n      headers: [\n        MockServer::KeyToMultiValue.new(name: \"content-type\", values: [\"text/plain\"])\n      ]\n    )\n  )\n)",
  "special-chars-escaping": "require 'mockserver-client'\n\nclient = MockServer::Client.new('localhost', 1080)\n\nclient.upsert(\n  MockServer::Expectation.new(\n    http_request: MockServer::HttpRequest.new(\n      method: \"GET\",\n      path: \"/a`b/c\\\"#d\",\n      body: \"line1\\nline2 \\\"quoted\\\" `tick`\"\n    ),\n    http_response: MockServer::HttpResponse.new(\n      status_code: 200,\n      body: \"resp \\\"with\\\" `back`tick and #hash\",\n      headers: [\n        MockServer::KeyToMultiValue.new(name: \"content-type\", values: [\"text/plain\"])\n      ]\n    )\n  )\n)",
  "capture-scenario-sideEffects": "require 'mockserver-client'\n\nclient = MockServer::Client.new('localhost', 1080)\n\nclient.upsert(\n  MockServer::Expectation.new(\n    http_request: MockServer::HttpRequest.new(\n      method: \"POST\",\n      path: \"/checkout\"\n    ),\n    http_response: MockServer::HttpResponse.new(\n      status_code: 200,\n      body: \"ok\",\n      headers: [\n        MockServer::KeyToMultiValue.new(name: \"content-type\", values: [\"text/plain\"])\n      ]\n    ),\n    after_actions: [\n      MockServer::AfterAction.new(\n        http_request: MockServer::HttpRequest.new(\n          method: \"POST\",\n          path: \"/audit\",\n          headers: [\n            MockServer::KeyToMultiValue.new(name: \"Host\", values: [\"audit.example.com\"])\n          ],\n          body: \"{\\\"logged\\\":true}\"\n        )\n      )\n    ],\n    capture: [\n      MockServer::CaptureRule.new(\n        source: \"jsonPath\",\n        expression: \"$.token\",\n        into: \"authToken\"\n      )\n    ],\n    scenario_name: \"login\",\n    scenario_state: \"START\",\n    new_scenario_state: \"DONE\"\n  )\n)",
  "steps-pipeline": "require 'mockserver-client'\n\nclient = MockServer::Client.new('localhost', 1080)\n\nclient.upsert(\n  MockServer::Expectation.new(\n    http_request: MockServer::HttpRequest.new(\n      method: \"GET\",\n      path: \"/pipeline\"\n    ),\n    steps: [\n      MockServer::ExpectationStep.new(\n        http_response: MockServer::HttpResponse.new(\n          status_code: 200,\n          body: \"step\"\n        ),\n        responder: true\n      ),\n      MockServer::ExpectationStep.new(\n        http_request: MockServer::HttpRequest.new(\n          path: \"/hook\"\n        ),\n        delay: MockServer::Delay.new(\n          time_unit: \"MILLISECONDS\",\n          value: 100\n        ),\n        timeout: MockServer::Delay.new(\n          time_unit: \"SECONDS\",\n          value: 2\n        ),\n        failure_policy: \"FAIL_FAST\"\n      )\n    ]\n  )\n)"
};
